{
    imports = [
        ./lang
        ./oil.nix
        ./lualine.nix
        ./telescope.nix
        ./treesitter.nix
        ./lsp.nix
        ./cmp.nix
        ./comment.nix
        ./colorizer.nix
        ./neogit.nix
        ./gitsigns.nix
        ./hop.nix
        ./fidget.nix
        ./trouble.nix
        ./indent-blankline.nix
        ./vim-surround.nix
        ./snippets.nix
        ./conform.nix
        ./lint.nix
        ./presence.nix
        ./web-devicons.nix
    ];
}
